### ISSUE TITLE
Upgrade to 5.6

### ISSUE THREAD

**Issue by DIXLTICMU** [MLnick/elasticsearch-vector-scoring#11]
It's actually fairly easy to upgrade to 5.6.... just replace the ES version number in the pom file to the actual ES 5.6.x version...

**Comment by DIXLTICMU** [comment]
Of course the plugin installation command changes to something like:

./bin/elasticsearch-plugin install file:<PATH>/elasticsearch-vector-scoring-5.6.4.zip

Assuming you are using ES 5.6.4, the minor version matters.

**Comment by lornsky** [comment]
Hello,can you tell me how to use in es 5.6？ thanks！

**Comment by MLnick** [comment]
Hi there - this functionality is now supported natively in ES: https://www.elastic.co/guide/en/elasticsearch/reference/current/dense-vector.html

Also see https://www.elastic.co/blog/text-similarity-search-with-vectors-in-elasticsearch.

See also an update to related Code Pattern on IBM Developer that illustrates a recommendation use case: IBM/elasticsearch-spark-recommender#54
