### ISSUE TITLE
Suggested update to vectorscoring.sh

### ISSUE THREAD

**Issue by DIXLTICMU** [MLnick/elasticsearch-vector-scoring#12]
I recommend doing an index refresh before you run your final scoring query in your example. My finding is that if you don't do that, you may not get all the test docs in your first pass, it takes some very shot time for ES to propagate your indexing changes before it makes them searchable.

**Comment by MLnick** [comment]
Hi there - most of this plugin functionality is now supported natively in ES: https://www.elastic.co/guide/en/elasticsearch/reference/current/dense-vector.html

Also see https://www.elastic.co/blog/text-similarity-search-with-vectors-in-elasticsearch.

See also an update to related Code Pattern on IBM Developer that illustrates a recommendation use case: IBM/elasticsearch-spark-recommender#54
