### ISSUE TITLE
Use Euclidean distance as similarity?

### ISSUE THREAD

**Issue by Stamenov** [MLnick/elasticsearch-vector-scoring#14]
Hello,

first of all kudos for the amazing idea for this plugin.
I am naively wondering it might be feasible to get the similar vectors (of texts) in terms of k-nn based on the Euclidean distance. The indexed vectors are the output of a NN language model, which I guess can also be factorized.

Greetings.

**Comment by MLnick** [comment]
Hi there - most of this plugin functionality is now supported natively in ES: https://www.elastic.co/guide/en/elasticsearch/reference/current/dense-vector.html

Also see https://www.elastic.co/blog/text-similarity-search-with-vectors-in-elasticsearch.

See also an update to related Code Pattern on IBM Developer that illustrates a recommendation use case: IBM/elasticsearch-spark-recommender#54
