### ISSUE TITLE
update for elasticsearch 5.x?

### ISSUE THREAD

**Issue by panyang** [MLnick/elasticsearch-vector-scoring#2]
Thanks for this cool plugin. Can you update for elasticsearch 5.x? or any tips to update it

**Comment by MLnick** [comment]
I've pushed https://github.com/MLnick/elasticsearch-vector-scoring/tree/es-5. Take a look and let me know if it works for you.

I targeted ES `5.3.0` and tested locally successfully.

**Comment by panyang** [comment]
I've test it on ES 5.3.0 and it works very well, thanks a lot.

**Comment by MLnick** [comment]
Great! `master` now targets ES 5.3, while I pushed branch `es-2.4` for legacy.

**Comment by ZEllison** [comment]
I use ES 5.3.0,java is 1.8.0_45;but install failed. log:ERROR: Unknown plugin elasticsearch-vector-scoring-5.3.0.zip

**Comment by MLnick** [comment]
@ZEllison can you reproduce the steps you're using to install? By the way see #3 for details of how to install the plugin from the Github Release url.

**Comment by ZEllison** [comment]
just by steps:
1、execute mvn package on my Mac, 
2、 transport the zip file to centos machine
3、execute elastic install command。

Finally, I used  " ./bin/elasticsearch-plugin install https://github.com/MLnick/elasticsearch-vector-scoring/releases/download/v5.3.0/elasticsearch-vector-scoring-5.3.0.zip" which solved my problem.

But, I don't understand the reason why the version compiled myself isn't ok.
