### ISSUE TITLE
Use GH releases to distribute compiled plugin?

### ISSUE THREAD

**Issue by olalonde** [MLnick/elasticsearch-vector-scoring#3]
Hi, it would be very helpful if you could distribute a compiled version of this plugin so that others can just install it with a URL.

**Comment by MLnick** [comment]
Let me look into it.

**Comment by MLnick** [comment]
@olalonde by the way (sorry it's late) but I made a [release](https://github.com/MLnick/elasticsearch-vector-scoring/releases/tag/v5.3.0) with a downloadable plugin ZIP.

You can install the latest version using `./bin/elasticsearch-plugin install https://github.com/MLnick/elasticsearch-vector-scoring/releases/download/v5.3.0/elasticsearch-vector-scoring-5.3.0.zip`
