### ISSUE TITLE
`elasticsearch` directory is missing in the plugin zip

### ISSUE THREAD

**Issue by acircuit** [MLnick/elasticsearch-vector-scoring#6]
I am using elastic search : 5.6.2. Whenever i try to install the plugin using : 

Install plugin in Elasticsearch: ELASTIC_HOME/bin/elasticsearch-plugin install file:///PROJECT_HOME/target/releases/elasticsearch-vector-scoring-5.3.0.zip (stop ES first).

I get an error: ERROR: `elasticsearch` directory is missing in the plugin zip
I am new to this. Please tell me if there is something wrong with my installation step or something wrong with the zip file?

**Comment by prakash7755** [comment]
Me to getting same error...

**Comment by MLnick** [comment]
Hi there. The plugin currently supports ES versions up to 5.4 (see https://github.com/MLnick/elasticsearch-vector-scoring#releases).

So you will need to download and install Elasticsearch 5.4 rather than 5.5/5.6.

**Comment by MLnick** [comment]
Hi there - most of this plugin functionality is now supported natively in ES: https://www.elastic.co/guide/en/elasticsearch/reference/current/dense-vector.html

Also see https://www.elastic.co/blog/text-similarity-search-with-vectors-in-elasticsearch.

See also an update to related Code Pattern on IBM Developer that illustrates a recommendation use case: IBM/elasticsearch-spark-recommender#54
