### ISSUE TITLE
Failed to compile inline script [payload_vector_score] using lang [native]

### ISSUE THREAD

**Issue by mickeysjm** [MLnick/elasticsearch-vector-scoring#7]
Hi Nick,

I have installed this plugin in my ElasticSearch 5.4.0 and enabled the inline script in elasticsearch.yml. The indexing phase works fine but I receive the following error when I issue a query. I paste the error message as following:

` "error" : {
    "root_cause" : [
      {
        "type" : "general_script_exception",
        "reason" : "Failed to compile inline script [payload_vector_score] using lang [native]"
      }
    ],
    "type" : "search_phase_execution_exception",
    "reason" : "all shards failed",
    "phase" : "query",
    "grouped" : true,
    "failed_shards" : [
      {
        "shard" : 0,
        "index" : "test",
        "node" : "1zCItkTwQX2ujhLc4TH0Hg",
        "reason" : {
          "type" : "query_shard_exception",
          "reason" : "script_score: the script could not be loaded",
          "index_uuid" : "T9hH9ZZaTZm21pLfv81eZQ",
          "index" : "test",
          "caused_by" : {
            "type" : "general_script_exception",
            "reason" : "Failed to compile inline script [payload_vector_score] using lang [native]",
            "caused_by" : {
              "type" : "illegal_argument_exception",
              "reason" : "Native script [payload_vector_score] not found"
            }
          }
        }
      }
    ]
  },
  "status" : 400
}
`

I wonder whether you have any idea on the potential reason behind this error.

Thanks.

**Comment by MLnick** [comment]
Have you installed the plugin? 

You need to follow the installation instructions in the README: https://github.com/MLnick/elasticsearch-vector-scoring#plugin-installation

**Comment by mickeysjm** [comment]
I install the plugin following your instruction. I mainly run the following command described in "Simple installation" section. 

`
ELASTIC_HOME/bin/elasticsearch-plugin install https://github.com/MLnick/elasticsearch-vector-scoring/releases/download/v5.4.0/elasticsearch-vector-scoring-5.4.0.zip
`

I don't run the commands described "build from source".

I double check and find that the plugin is registered at Elasticsearch startup. However, I still receive this error.

**Comment by tardunge** [comment]
Even i had the same issue but with 5.3.0
Upgrading ES to 5.4.0 and building the package from source resolved this problem.

**Comment by guoliu** [comment]
Same issue here with ES 5.4.0., installed with instructions in "simple installation". @manoj2378 have you found what the root cause is, or any methods to make it work without building from source?

**Comment by MLnick** [comment]
Hi there - most of this plugin functionality is now supported natively in ES: https://www.elastic.co/guide/en/elasticsearch/reference/current/dense-vector.html

Also see https://www.elastic.co/blog/text-similarity-search-with-vectors-in-elasticsearch.

See also an update to related Code Pattern on IBM Developer that illustrates a recommendation use case: IBM/elasticsearch-spark-recommender#54
