### ISSUE TITLE
How do i convert a string to vectors for the plugin

### ISSUE THREAD

**Issue by c-chaitanya** [MLnick/elasticsearch-vector-scoring#9]
I'm trying to score and retrieve relevant documents in elasticsearch 5.4. I tried out the demo in read me and everything works fine. Now I want to convert a string to vectors and save it in elasticsearch.
    curl -s -XPUT 'http://localhost:9200/test/movies/1?pretty' -d '
    {
        "@model_factor":"0|1.2 1|0.1 2|0.4 3|-0.2 4|0.3",
        "name": "Test 1"
    }'
Can i know how you got the above vectors in @model_factor. Can you share something on converting string to vectors?.

**Comment by MLnick** [comment]
Hi - please take a look at https://github.com/IBM/elasticsearch-spark-recommender which illustrates a more complete example of how to use this plugin together with Apache Spark for model training. The Jupyter notebook there contains examples of utility functions for turning an array or list into the correct string format, and back again as required.

**Comment by c-chaitanya** [comment]
Hey, thank you for the quick reply. I went through the code, but i have a slightly different usecase. I have a list of question answers stored in elastic search. I want to query the question such that it would return that relevant document( answer associated with that question). How would you suggest that i store the documents to gain the best of the plugin? How should my vector representation be? How do i convert my string to a vector?

I've searched hard and couldn't find/understand a way to convert my string(questions like " how do i make a telephone call ") to the vector representation in the example. Is it a comma seperated word2vec vectors?. Any help would be greatly appreciated.

A single sample of my document
    PUT /test/test/1
    {
        "account_id": 12345,
        "question": "who discovered america",
        "answer": " amerigo vespuchi ",
    }

**Comment by MLnick** [comment]
Ok, I see.

Currently the plugin supports scoring with single vectors - i.e. a single query vector against a single vector in each document. It would be possible to expand that within the plugin to score multiple vectors.

However, you mention Word2Vec or some other embedding model. You could try to use the average word vector for each query and document, and that would work with this plugin. Whether that would give you acceptable model performance, I am not certain.

**Comment by c-chaitanya** [comment]
Ok, that answers it, will be using word2vec for vectors. 
Will be closing the topic. 
Thank you for the quick reply
